### ISSUE TITLE
PHSCore.apply_connectors does not move cu/cy cols.

### ISSUE THREAD

**Issue by FabricioS** [pyphs/pyphs#29] opened 2017-04-20 14:27 UTC
PHSCore.apply_connectors does not move cols and rows corresponding to cu and cy at the end of the matrix M before calling the [move_connector method](https://github.com/afalaize/pyphs/blob/master/pyphs/core/core.py#L497). But the [move_connector function (in struct_tools.py)](https://github.com/afalaize/pyphs/blob/master/pyphs/core/struc_tools.py#L57) uses an offset core.dims.x()+core.dims.w()+core.dims.y(), so that the cu and cy component are expected to be located at the last rows and columns of M

**Comment by afalaize** [comment] 2017-04-20 14:59
Oh... yes. thanks. I will have a look on that point soon.

**Comment by afalaize** [comment] 2017-04-21 22:33
@FabricioS: can you pull the branch FabricioS-development and run the example 'connectors'?
It merges your pr #27 and should close this issue.

**Comment by FabricioS** [comment] 2017-04-22 07:37
Seems ok for my own testcase, but the connectors examples fails : 
```
%run pyphs/examples/connectors/connectors.py
Read netlist phs1.net
from folder /home/fab/Professionnel/src/pyphs/pyphs/examples/connectors/
Build graph ...
Build graph M...
Build graph S11...
Build graph S12...
Build core ...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/fab/Professionnel/src/pyphs/pyphs/examples/connectors/connectors.py in <module>()
     21 label = 'phs1'
     22 # build simple PHSCores
---> 23 c1 = netlist2core(netlist_path(label))
     24 print('c1.M={}'.format(c1.M))
     25 

/home/fab/Professionnel/src/pyphs/pyphs/graphs/__init__.py in netlist2core(netlist)
      8         netlist = PHSNetlist(netlist)
      9     graph = PHSGraph(netlist=netlist)
---> 10     return graph.buildCore()

/home/fab/Professionnel/src/pyphs/pyphs/graphs/graph.py in buildCore(self, verbose, plot, apply_connectors)
     62         core = self.core.__deepcopy__()
     63         if apply_connectors:
---> 64             core.apply_connectors()
     65         return core
     66 

/home/fab/Professionnel/src/pyphs/pyphs/core/core.py in apply_connectors(self)
    516         M_connectors = G_connectors * Mswitch * O_connectors
    517         # Store new structure
--> 518         self.M = M[:nxwy, :nxwy] + M_connectors
    519 
    520         # clean

/usr/lib/python3/dist-packages/sympy/core/decorators.py in binary_op_wrapper(self, other)
    116                     else:
    117                         return f(self)
--> 118             return func(self, other)
    119         return binary_op_wrapper
    120     return priority_decorator

/usr/lib/python3/dist-packages/sympy/matrices/dense.py in __add__(self, other)
    537     @call_highest_priority('__radd__')
    538     def __add__(self, other):
--> 539         return super(DenseMatrix, self).__add__(_force_mutable(other))
    540 
    541     @call_highest_priority('__add__')

/usr/lib/python3/dist-packages/sympy/matrices/matrices.py in __add__(self, other)
    577             ret = [S.Zero]*A.rows
    578             for i in range(A.shape[0]):
--> 579                 ret[i] = [j + k for j, k in zip(alst[i], blst[i])]
    580             rv = classof(A, B)._new(ret)
    581             if 0 in A.shape:

/usr/lib/python3/dist-packages/sympy/matrices/matrices.py in <listcomp>(.0)
    577             ret = [S.Zero]*A.rows
    578             for i in range(A.shape[0]):
--> 579                 ret[i] = [j + k for j, k in zip(alst[i], blst[i])]
    580             rv = classof(A, B)._new(ret)
    581             if 0 in A.shape:

/usr/lib/python3/dist-packages/sympy/core/decorators.py in __sympifyit_wrapper(a, b)
     75                 if not hasattr(b, '_op_priority'):
     76                     b = sympify(b, strict=True)
---> 77                 return func(a, b)
     78             except SympifyError:
     79                 return retval

/usr/lib/python3/dist-packages/sympy/core/numbers.py in __add__(self, other)
    928         if isinstance(other, Number):
    929             rhs, prec = other._as_mpf_op(self._prec)
--> 930             return Float._new(mlib.mpf_add(self._mpf_, rhs, prec, rnd), prec)
    931         return Number.__add__(self, other)
    932 

/usr/lib/python3/dist-packages/mpmath/libmp/libmpf.py in mpf_add(s, t, prec, rnd, _sub)
    766         return t
    767     if sman:
--> 768         return normalize1(ssign, sman, sexp, sbc, prec or sbc, rnd)
    769     return s
    770 

TypeError: argument is not an mpz

In [2]: %debug
ipdb> 
> /home/fab/Professionnel/src/pyphs/pyphs/core/core.py(518)apply_connectors()
    516         M_connectors = G_connectors * Mswitch * O_connectors
    517         # Store new structure
--> 518         self.M = M[:nxwy, :nxwy] + M_connectors
    519 
    520         # clean

ipdb> p M
Matrix([
[   0, 1.0, -1.0],
[-1.0,   0,    0],
[ 1.0,   0,    0]])
ipdb> p type(M), M.shape
(<class 'sympy.matrices.dense.MutableDenseMatrix'>, (3, 3))
ipdb> p M_connectors
Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])
ipdb> p type(M_connectors)
<class 'sympy.matrices.dense.MutableDenseMatrix'>

```

The changes in apply_connector lead to troubles in the creation of c1 itself ?!

**Comment by afalaize** [comment] 2017-04-22 08:32
It should not.
Since the connection now seems to perform well, I close this issue and reopen the issue #26 regarding the very strange error `TypeError: argument is not an mpz`. I can not reproduce this error on mac OSX. Please, give informations about your environement in issue #26.

**Closed as completed by afalaize** 2017-04-22 08:32 UTC

**Comment by FabricioS** [comment] 2017-05-05 13:35
Hi,
as far as I understand, the commit 1255ef315e432819 solves the issue. Two comments:
1. it seems possible to add a connector using symbols that are not already listed as inputs or outputs. Is this useful? It seems that it only delays the error that will then raise during the apply_connectors call.
2. It moves the rows/cols corresponding to cu/cy within the add_connector method. It thus modifies the M matrix at a early stage, in comparison with the previous process where modifications to M only occured within the apply_connector. As a consequence, before the call to apply_connector, the M matrix may be in a weird half-transformed state that only partly reflects the structure.

**Comment by afalaize** [comment] 2017-05-07 00:24
Regarding point 1: This was used in the "graph'n dictionary" side of pyphs. However, you're right: this is not absolutely necessary and could be the source for bugs, so I open a [branch](https://github.com/afalaize/pyphs/tree/simplify_call_to_add_connector) to forbid this practice and to simplify the call to be somethong like `add_connector((i1, i2), alpha)` with `i1` and `i2` the indices in `core.y` of the ports to connect.

Regarding point 2: the add_connector method calls the port2connector function which is just a permutation of rows and columns of M, with the total input (u, cu) and total ouput (y, cy), so the structure of M is not broken.

**Comment by FabricioS** [comment] 2017-05-09 07:43
Hi,
1. Sorry for being the complaining user that does not use the graph'n'dict way :)
Thanks for the simplification of the signature of the add_connector method.
2. OK, I agree
