### ISSUE TITLE
MPZ TypeError in graph analysis

### ISSUE THREAD

**Issue by TristanLbrn** [pyphs/pyphs#26] opened 2017-04-11 16:05 UTC
pyphs 0.1.9.7.3
python 2.7.9
sympy 1.0

Error occurs while running the DLC  described in the tutorial
[https://afalaize.github.io/pyphs/#graphanalysis2016](url)
- Script

```
import pyphs
netlist = pyphs.PHSNetlist('dlc.net')
graph = pyphs.PHSGraph(netlist)
core = graph.buildCore()
```

- Output

```

  File /pyphs/graphs/graph.py", line 53, in buildCore
    core.apply_connectors()

  File "/pyphs/core/core.py", line 516, in apply_connectors
    self.M = M[:nxwy, :nxwy] + M_connectors

  File "/sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)

  File "/sympy/matrices/dense.py", line 539, in __add__
    return super(DenseMatrix, self).__add__(_force_mutable(other))

  File "/sympy/matrices/matrices.py", line 579, in __add__
    ret[i] = [j + k for j, k in zip(alst[i], blst[i])]

  File "/sympy/core/decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)

  File "/sympy/core/numbers.py", line 930, in __add__
    return Float._new(mlib.mpf_add(self._mpf_, rhs, prec, rnd), prec)

  File "/mpmath/libmp/libmpf.py", line 768, in mpf_add
    return normalize1(ssign, sman, sexp, sbc, prec or sbc, rnd)

TypeError: argument is not an mpz


```

**Comment by afalaize** [comment] 2017-04-11 16:14
Weird! cannot reproduce.
OS?
Try an update of dependencies (see [requirements.txt](https://github.com/afalaize/pyphs/blob/master/requirements.txt) for required versions)

**Comment by TristanLbrn** [comment] 2017-04-11 17:11
OS is Linux with distribution Debian 8. 
All packages meet requirements except matplotlib (but that should not interfere here).
However this script works on Ubuntu 14.04, with the same python and pyphs versions.

Must be an internal error from my Debian system, I close this issue.

**Comment by afalaize** [comment] 2017-04-22 08:37
Reopen based on the test of @FabricioS in issue #29

**Comment by FabricioS** [comment] 2017-04-22 09:08
I am using python3 packages from the Debian sid repositories.
For instance python3-sympy is 1.0-3.
The error may be related to this one :
https://github.com/sympy/sympy/issues/7457  ?

What is weird is that the summation of the two matrices M and M_connectors does not cause any troubles when connecting two PHS created otherwise (i.e., not from netlist)

**Comment by afalaize** [comment] 2017-04-22 10:29
@FabricioS : Can you try the example thielesmall?
I suspect the problem is the use of `core.apply_connectors` with an empty `core.connectors`;
If this is the case, a simple fix is a test for the connectors dimension in `core.apply_connectors`.
I will try to reproduce in a virtual machine.

**Comment by FabricioS** [comment] 2017-04-25 07:19
The thielesmall example raises the same error despite the connectors attributes not being empty.
```
In [1]: %run pyphs/examples/thielesmall/thielesmall.py 
   ...: 
Read netlist thielesmall.net
from folder /home/fab/Professionnel/src/pyphs/pyphs/examples/thielesmall/
Build graph ...
Build graph IN...
Build graph R...
Build graph L...
Build graph T...
Build graph M...
Build graph K...
Build graph A...
Build core ...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/fab/Professionnel/src/pyphs/pyphs/examples/thielesmall/thielesmall.py in <module>()
     21 
     22 graph = PHSGraph(netlist=netlist)
---> 23 core = graph.buildCore()
     24 
     25 if __name__ == '__main__':

/home/fab/Professionnel/src/pyphs/pyphs/graphs/graph.py in buildCore(self, verbose, plot, apply_connectors)
     62         core = self.core.__deepcopy__()
     63         if apply_connectors:
---> 64             core.apply_connectors()
     65         return core
     66 

/home/fab/Professionnel/src/pyphs/pyphs/core/core.py in apply_connectors(self)
    516         M_connectors = G_connectors * Mswitch * O_connectors
    517         # Store new structure
--> 518         self.M = M[:nxwy, :nxwy] + M_connectors
    519 
    520         # clean

/usr/lib/python3/dist-packages/sympy/core/decorators.py in binary_op_wrapper(self, other)
    116                     else:
    117                         return f(self)
--> 118             return func(self, other)
    119         return binary_op_wrapper
    120     return priority_decorator

/usr/lib/python3/dist-packages/sympy/matrices/dense.py in __add__(self, other)
    537     @call_highest_priority('__radd__')
    538     def __add__(self, other):
--> 539         return super(DenseMatrix, self).__add__(_force_mutable(other))
    540 
    541     @call_highest_priority('__add__')

/usr/lib/python3/dist-packages/sympy/matrices/matrices.py in __add__(self, other)
    577             ret = [S.Zero]*A.rows
    578             for i in range(A.shape[0]):
--> 579                 ret[i] = [j + k for j, k in zip(alst[i], blst[i])]
    580             rv = classof(A, B)._new(ret)
    581             if 0 in A.shape:

/usr/lib/python3/dist-packages/sympy/matrices/matrices.py in <listcomp>(.0)
    577             ret = [S.Zero]*A.rows
    578             for i in range(A.shape[0]):
--> 579                 ret[i] = [j + k for j, k in zip(alst[i], blst[i])]
    580             rv = classof(A, B)._new(ret)
    581             if 0 in A.shape:

/usr/lib/python3/dist-packages/sympy/core/decorators.py in __sympifyit_wrapper(a, b)
     75                 if not hasattr(b, '_op_priority'):
     76                     b = sympify(b, strict=True)
---> 77                 return func(a, b)
     78             except SympifyError:
     79                 return retval

/usr/lib/python3/dist-packages/sympy/core/numbers.py in __add__(self, other)
    928         if isinstance(other, Number):
    929             rhs, prec = other._as_mpf_op(self._prec)
--> 930             return Float._new(mlib.mpf_add(self._mpf_, rhs, prec, rnd), prec)
    931         return Number.__add__(self, other)
    932 

/usr/lib/python3/dist-packages/mpmath/libmp/libmpf.py in mpf_add(s, t, prec, rnd, _sub)
    766         return t
    767     if sman:
--> 768         return normalize1(ssign, sman, sexp, sbc, prec or sbc, rnd)
    769     return s
    770 

TypeError: argument is not an mpz

In [2]: %debug
[...]
ipdb> 
> /home/fab/Professionnel/src/pyphs/pyphs/core/core.py(518)apply_connectors()
    516         M_connectors = G_connectors * Mswitch * O_connectors
    517         # Store new structure
--> 518         self.M = M[:nxwy, :nxwy] + M_connectors
    519 
    520         # clean

ipdb> p self.connectors
[{'u': (uT1, uT2), 'y': (yT1, yT2), 'alpha': Bl}]
ipdb> 

```

**Comment by afalaize** [comment] 2017-06-28 12:19
Finally, I asked in sympy gogole group.
Answer: "This was fixed accidentally in https://github.com/sympy/sympy/pull/11862"
Can anyone check for the answer [here](https://groups.google.com/forum/#!topic/sympy/d0zjnsUe0ks) and continue investigations?

**Comment by FabricioS** [comment] 2017-06-28 12:47
The trouble is calling mpmath.libmp.libmpf.normalize1 with the 2nd argument (man) not being a mpz instance.
The pull request pointed in the sympy group (https://github.com/sympy/sympy/pull/11862) introduces a cast : the 2nd argument is now MPZ(man) with MPZ imported from mpmath.libmp.backend.
This fixes the problem, but I do not know if the fix should be merge in mpmath (a safety check in mpmath.libmp.libmpf.normalize1), in sympy (should we correct the _mpf_ attribute of numbers ?) or if we can fix it in pyphs...

**Comment by afalaize** [comment] 2017-06-28 19:31
Thank you
Should not we just wait for this cast to appear in the next sympy release, and update the pyphs requirements to point this release (since we do not call mpmath explicitely)?

**Comment by FabricioS** [comment] 2017-06-28 20:11
Patch https://github.com/sympy/sympy/pull/11862 accidentally fixed the problem for some operations. Another patch has been suggested (https://github.com/sympy/sympy/pull/10674) but still not merged.

**Comment by afalaize** [comment] 2017-07-04 11:13
The [sympy release 1.1](https://github.com/sympy/sympy/releases/tag/sympy-1.1rc1) is now available for testing. Could anyone perform a test and confirm it solves this issue?

**Comment by TristanLbrn** [comment] 2017-07-04 14:00
The issue still occurs for me, with the Thiele-Small example and pyphs '0.1.9.9.4'.
It seems that the argument type in mpmath has been left unchanged in sympy '1.1rc1'.
```
import sympy

sympy.__version__
Out[3]: '1.1rc1'

runfile('/net/inavouable/u.anasynth/lebrun/pyphs-development/pyphs/examples/thielesmall/thielesmall.py', wdir='/net/inavouable/u.anasynth/lebrun/pyphs-development/pyphs/examples/thielesmall')
Read netlist thielesmall.net
from folder /net/inavouable/u.anasynth/lebrun/pyphs-development/pyphs/examples/thielesmall/
pass "#=======================  INPUTS  ========================#"
read "electronics.source      IN  ('A', '#'):             type=voltage;"
pass "#"
pass "#=====================  ELECTRONICS  =====================#"
read "electronics.resistor    R   ('A', 'B'):             R=('R', 5.9);"
read "electronics.inductor    L   ('B', 'C'):             L=('L', 2.36*1e-3);"
pass "#"
pass "#======================  CONNECTOR  ======================#"
read "connectors.transformer  T   ('C', '#', 'D', '#'):   alpha=('Bl', 16.37);"
pass "#"
pass "#======================  MECHANICS  ======================#"
read "mechanics.mass          M   ('D',):                 M=('M', 0.075);"
read "mechanics.stiffness     K   ('D', '#'):             K=('K', 1e4);"
read "mechanics.damper        A   ('D', '#'):             A=('A', 10.);"
pass ""
Build graph IN...
Build graph R...
Build graph L...
Build graph T...
Build graph M...
Build graph K...
Build graph A...
Build graph thielesmall...
Build core thielesmall...
Traceback (most recent call last):

  File "<ipython-input-4-eb6c67bedf5a>", line 1, in <module>
    runfile('/net/inavouable/u.anasynth/lebrun/pyphs-development/pyphs/examples/thielesmall/thielesmall.py', wdir='/net/inavouable/u.anasynth/lebrun/pyphs-development/pyphs/examples/thielesmall')

  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)

  File "/net/inavouable/u.anasynth/lebrun/pyphs-development/pyphs/examples/thielesmall/thielesmall.py", line 20, in <module>
    core = graph.buildCore()

  File "/net/inavouable/u.anasynth/lebrun/pyphs-development/pyphs/graphs/graph.py", line 79, in buildCore
    core.connect()

  File "/net/inavouable/u.anasynth/lebrun/pyphs-development/pyphs/core/core.py", line 611, in connect
    self.M = types.matrix_types[0](self.M[:nxwy, :nxwy] + M_connectors)

  File "/net/inavouable/u.anasynth/lebrun/python_packages/sympy-1.1rc1/sympy/core/decorators.py", line 132, in binary_op_wrapper
    return func(self, other)

  File "/net/inavouable/u.anasynth/lebrun/python_packages/sympy-1.1rc1/sympy/matrices/common.py", line 1960, in __add__
    return a._eval_add(b)

  File "/net/inavouable/u.anasynth/lebrun/python_packages/sympy-1.1rc1/sympy/matrices/sparse.py", line 266, in _eval_add
    sum = self._smat.get(key, zero) + other._smat.get(key, zero)

  File "/net/inavouable/u.anasynth/lebrun/python_packages/sympy-1.1rc1/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)

  File "/net/inavouable/u.anasynth/lebrun/python_packages/sympy-1.1rc1/sympy/core/numbers.py", line 1155, in __add__
    return Float._new(mlib.mpf_add(self._mpf_, rhs, prec, rnd), prec)

  File "/usr/lib/python2.7/dist-packages/mpmath/libmp/libmpf.py", line 768, in mpf_add
    return normalize1(ssign, sman, sexp, sbc, prec or sbc, rnd)

TypeError: argument is not an mpz

```

More precisely, in debug mode:
```
ipdb> M_connectors
Matrix([
[0,      0,       0, 0, 0, 0],
[0,      0, -1.0*Bl, 0, 0, 0],
[0, 1.0*Bl,       0, 0, 0, 0],
[0,      0,       0, 0, 0, 0],
[0,      0,       0, 0, 0, 0],
[0,      0,       0, 0, 0, 0]])

ipdb> self.M

ipdb> Matrix([
[  0,    0, -1.0,   0,    0,   0,    0,   0],
[  0,    0,    0,   0, -1.0, 1.0, -1.0,   0],
[1.0,    0,    0, 1.0,    0,   0,    0, 1.0],
[  0,    0, -1.0,   0,    0,   0,    0,   0],
[  0,  1.0,    0,   0,    0,   0,    0,   0],
[  0, -1.0,    0,   0,    0,   0,    0,   0],
[  0,  1.0,    0,   0,    0,   0,    0,   0],
[  0,    0, -1.0,   0,    0,   0,    0,   0]])
```
the error occurs when adding M_connectors and self.M:
```
ipdb> M_connectors + self.M[:nxwy, :nxwy]
*** TypeError: argument is not an mpz
```

**Comment by afalaize** [comment] 2017-07-04 15:36
Thank you for taking the time to test.
I relayed to the sympy group [here](https://groups.google.com/forum/#!topic/sympy/d0zjnsUe0ks).

**Comment by FabricioS** [comment] 2017-07-06 08:25
I managed to track down the bug to a problem in the copy of the M matrix in the graph.buildCore()
See bug in the sympy repository : https://github.com/sympy/sympy/issues/12895

**Comment by afalaize** [comment] 2017-07-08 10:58
Thank you. Known I think we should follow the advice [here](https://github.com/sympy/sympy/pull/7674) to not use deepcopy. In [this commit](https://github.com/afalaize/pyphs/commit/e84b790116dfb6bf772975712050f1557c4be2fe), I use copy.copy instead of copy.deepcopy. Tests pass and I hope it will solve this issue.

**Comment by TristanLbrn** [comment] 2017-07-11 08:23
Works also on my Debian with `copy.copy` from [the commit](https://github.com/afalaize/pyphs/commit/e84b790116dfb6bf772975712050f1557c4be2fe). @FabricioS , maybe you could do a final check, but I think this closes the issue, well done!


```
Read netlist thielesmall.net
from folder /net/inavouable/u.anasynth/lebrun/pyphs-development/pyphs/examples/thielesmall/
pass "#=======================  INPUTS  ========================#"
read "electronics.source      IN  ('A', '#'):             type=voltage;"
pass "#"
pass "#=====================  ELECTRONICS  =====================#"
read "electronics.resistor    R   ('A', 'B'):             R=('R', 5.9);"
read "electronics.inductor    L   ('B', 'C'):             L=('L', 2.36*1e-3);"
pass "#"
pass "#======================  CONNECTOR  ======================#"
read "connectors.transformer  T   ('C', '#', 'D', '#'):   alpha=('Bl', 16.37);"
pass "#"
pass "#======================  MECHANICS  ======================#"
read "mechanics.mass          M   ('D',):                 M=('M', 0.075);"
read "mechanics.stiffness     K   ('D', '#'):             K=('K', 1e4);"
read "mechanics.damper        A   ('D', '#'):             A=('A', 10.);"
pass ""
Build graph IN...
Build graph R...
Build graph L...
Build graph T...
Build graph M...
Build graph K...
Build graph A...
Build graph thielesmall...
Build core thielesmall...

In [14]: core.J()
Out[14]: 
Matrix([
[  0,      0,    -1.0,   0,    0,   0],
[  0,      0, -1.0*Bl,   0, -1.0, 1.0],
[1.0, 1.0*Bl,       0, 1.0,    0,   0],
[  0,      0,    -1.0,   0,    0,   0],
[  0,    1.0,       0,   0,    0,   0],
[  0,   -1.0,       0,   0,    0,   0]])
```

**Comment by FabricioS** [comment] 2017-07-11 10:05
Hi,
it's OK for me. The `_mpf_` attribute of floating values of the matrix is preserved by the copy.
Bug closed!

**Closed as completed by FabricioS** 2017-07-11 10:05 UTC
Labels: bug
